### ISSUE TITLE
index page content and links to other related content

### ISSUE THREAD

**Issue by lanceman2** [vtwireless/HLSI#10]
It would make me warm a fuzzy if the index page had a paragraph with links on it to related information that are not served by https://vtwireless.github.io/HLSI/

Maybe links back to canvas, and links to the HLSI homepage (if it exists).   Maybe it is the HLSI homepage.

Add a link to the source repo???

Maybe info about how this content may be used, and distributed.

Answer the question: How is this content related to the content on canvas?

Currently the page gives me no idea what the point of it is.  It's very disjoint.  One paragraph, with links, would go a long way.

This is an obvious void that needs filling, and so this "ticket" exists.

**Comment by Don-Roberts** [comment]
Fixed
