### ISSUE TITLE
SINR calculation in exercise_interference_2.html

### ISSUE THREAD

**Issue by carldietrich2** [vtwireless/HLSI#2]
The SINR calculation in the new interference exercise works for SNR in the non-interference case, but there appears to be a problem with the interference calculation.
 
I changed line 127 to the following and this yields reasonable SINR values for a range of signal bandwidths and power levels:  
 
    return ((f1-f0)/bw)*Math.pow(10.,(gn_int/10.))/bw_int;

I have not checked in the updated code.  The normalizations were arrived at empirically by comparing displayed SINR with expected SINR for equal signal and interference bandwidths and powers, and then with equal powers but different bandwidths for the signal and interference.  I have not yet had time to trace through the code to understand fully why the normalization is needed.  Even if the resulting SINR is correct for all cases, there might be more appropriate places in the code to add the normalizations.
 
To enable testing in the case of nearly equal signal and interference powers and bandwidths, I also changed the minimum signal bandwidth to 0.4 and increased the maximum signal gain to 20 dB.

**Comment by jgaeddert** [comment]
Resolved with df03121d8a03203a09b09e9bd80008a103b3d1a0
