### ISSUE TITLE
Refactor SINR calculation code

### ISSUE THREAD

**Issue by carldietrich2** [vtwireless/HLSI#32]
Put all SINR calculation code in a function.  
Also, apply any scaling factors used to display data separately from the SINR calculation.

**Comment by carldietrich2** [comment]
Future step is to update all simulations that use SINR or SNR to use the new SINR function, then check each simulation and compare against main branch as needed to ensure that the refactored code is not breaking any of the simulations.

**Comment by npolys** [comment]
Basic (ideal filter) is refactored and now a method on the signal object ; new SINR calcs for the other cases 
 any require this methods to take parameters
