### ISSUE TITLE
exercise_capacity_1.html SNR

### ISSUE THREAD

**Issue by carldietrich2** [vtwireless/HLSI#5]
The indicated SNR appears to be 10 dB too high for Bandwidth = 0.1 and 20 dB too high for Bandwidth = 0.9.

**Comment by jgaeddert** [comment]
I didn't create this exercise, but #6 addressed this by compensating for signal bandwidth. This exercise might be OBE at this point.

**Comment by jgaeddert** [comment]
exercise removed. Ticket OBE
