### ISSUE TITLE
exercise_path_loss.html -- user must click on marker outline to move marker

### ISSUE THREAD

**Issue by carldietrich2** [vtwireless/HLSI#7]

**Comment by jgaeddert** [comment]
This is a consequence for defining the overall svg path style in `base.css`. I will need to subclass the maker in css to allow it to have a different style. Looking into this now.

**Comment by jgaeddert** [comment]
Changed stylesheet to specify options for each line type in 91a6f5e0c40832806b6a0f709d3cb7bbca196f22. This probably breaks the noise and capacity 1 exercises, but I wasn't sure if we wanted to hold on to these.

**Comment by jgaeddert** [comment]
Closing this issue for now. If there are issues with other exercises due to the stylesheet changes, we can address those separately.
