### ISSUE TITLE
Pages at https://vtwireless.github.io/HLSI/ are not consistant

### ISSUE THREAD

**Issue by lanceman2** [vtwireless/HLSI#9]
The basic problem is that index.html and the links and titles of things are not consistent, and so if I do any referring to them, my reference will be nonsensical.   You just need to look at titles and file names and make it make more sense.  You just need to browse/edit with an eye for consistency.  You need to make the version of the pages at https://vtwireless.github.io/HLSI/ reasonable/rational.

I can send specifics if you need that, but I think the needed edits are very obvious.  Links with <a> text </a> that do not match page content, and stuff like that.  I'm building web interfaces to "real" USRPs in CRTS that mirror the exercises at https://vtwireless.github.io/HLSI/ , but if the words are a jumble at https://vtwireless.github.io/HLSI/, I have difficulty mirroring it or defining my task.

Consider the analogy: I'm a robot and your task output is input to my task, and now I have an input syntax error.

--lance

**Comment by Don-Roberts** [comment]
Fixed - the mismatch in Series 2
